### PR TITLE
Buy tv show

### PR DESCRIPTION
**Pull request by KAMiKAZOW**
That thing:

buy_TV_show

### CODE REVIEW

**Comment by mchangrh** [comment]
secondary seems to be very generic, not sure if I trust it to not conflict, especially not to the sponsorblock list.

**Comment by mchangrh** [comment]
https://github.com/mchangrh/yt-neuter/blob/main/yt-neuter.txt#L421-L422 already caught by universal-watch-card-renderer

**Comment by KAMiKAZOW** [comment]
> https://github.com/mchangrh/yt-neuter/blob/main/yt-neuter.txt#L421-L422 already caught by universal-watch-card-renderer

Can you add that to the Sponsorblock ruleset as well?

**Comment by mchangrh** [comment]
I'd rather not since it also encompasses featured channels, and I want to keep the sponsorblock list as permissive and aggressive as possible

**Pull request closed without merging**
