### PR TITLE
Hide AI-generated video summary

### PR DESCRIPTION
**Pull request by adolfgatonegro**
Hides the new AI-generated video summary that appears under the video description box.

### CODE REVIEW

**Comment by mchangrh** [comment]
what an awful way to find out that this exists. Can you send a video that has it?

**Comment by adolfgatonegro** [comment]
Don't know if they've rolled the feature out for everyone, but [this video](https://www.youtube.com/watch?v=YbQu_guop7M) has the AI summary for me.

Adding a screenshot, just in case it's not yet showing up for everyone:

**Comment by mchangrh** [comment]
seems to be very inconsistent but confirmed via a cloudflare radar scanner

https://radar.cloudflare.com/de-de/scan/cf76139a-de26-407d-9f39-820f24ae81c4/dom

**Comment by mchangrh** [comment]
https://www.youtube.com/watch?v=nM9zHvIuuC0 was also another candidate that was brought up

**Comment by adolfgatonegro** [comment]
> https://www.youtube.com/watch?v=nM9zHvIuuC0 was also another candidate that was brought up

Quite inconsistent, yes. I don't see it under that video, but here's another one I'm seeing: https://www.youtube.com/watch?v=bLyQdSeKr9Q. It's been showing up under videos here and there for about a week.

**Pull request merged**
